### ISSUE TITLE
Using picoquic to implement DNS/QUIC

### ISSUE THREAD

**Issue by gholamw** [private-octopus/picoquic#100]
Hi, 
I want to use this library for my final year project. I'm trying to implement DNS/QUIC. I tried to run the code and make a small test by running both client and server. At some point, the server stops the connection, produce an error message " [picoquic_retransmit_needed]: Too many retransmits, disconnect" and closes the connection. I was unclear on how to stop the server from closing the connection, as I want to establish the connection and keep both client and server running, where client will listen to DNS queries and forward them to the server. Also, I wasn't even sure if the connection has been established correctly between client and server. If you can point me to some direction it would be really appreciated. Thanks.

**Comment by huitema** [comment]
Hello Wessam,

That's an interesting project! Picoquic is still at the prototype stage, and it is possible there is some kind of bug in my code. I would like to write a small test that reproduces your experience. Can I somehow see your code? Either paste it here, of if you prefer to keep it private send a copy by email to huitema@huitema.net.

-- Christian Huitema

**Comment by huitema** [comment]
Sorry, I misunderstood the issue. Are you just using picoquicdemo?

**Comment by huitema** [comment]
OK, I think I fixed the issue. There was a problem in the client code. If the server was sending packets really quickly, the client would just process the received packets and only send responses very rarely. This could lead to the client not sending timely acknowledgements, the server retransmitting packets, and the connection eventually breaking. Please tell me if you still see the problem.

**Comment by gholamw** [comment]
Hello Christian, 
Yes i'm using picoquicdemo to implement DNS/QUIC. I've tested the code again, but it seems that the problem still exist. Maybe it would be helpful to attach a screenshot of the server.  Here is the link of the screenshot: https://imgur.com/a/Eb1OQ

I really appreciate your help. Thank you.

**Comment by huitema** [comment]
Yes, I see the error message on the server. For better debugging, could you do the following:

1) Start the server with the -1 option and capture output, e.g.:
       picoquicdemo -p 4433 -1 >server_log.txt

2) Start the client with a -l option, as in:
       picoquicdemo -l client_log.txt localhost 4433

This will produce a trace of packets at both ends, which can then be used to understand the issue.

**Comment by huitema** [comment]
Before you do that, please make sure that you update to the latest version -- I just pushed a series of small fixes related to MTU handling.

**Comment by huitema** [comment]
Closing as there is no follow-up on this issue.
